import "./globals.css";
import { Inter } from "next/font/google";
import Header from "../components/header/header";
import Footer from "../components/footer/footer"

import {Be_Vietnam_Pro} from 'next/font/google'

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const BeVietnamPro  = Be_Vietnam_Pro ({
  weight: ['400', '500', '600', '700'],
  style: ['normal'], 
  subsets: ['latin'], 
  display: 'swap',
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">  
    <head>
        <style>{`
          @import url('https://fonts.googleapis.com/css2?family=Be+Vietnam+Pro:wght@400;500;600;700&display=swap');
        `}</style>
      </head>
      <body className={`${inter.className}`}>
        <Header />
        {children}        
    <Footer />
      </body>
    </html>
  );
}
